### ISSUE TITLE
Add bèta link to Nightscout Status homepage

### ISSUE THREAD

**Issue by nielsmaerten** [nielsmaerten/gluco-check#84]
**I'm submitting a ...**  
- feature request

**Description**  
- We should add a link to the homepage of Nightscout Status, informing users that Gluco Check is now in beta and they can try it out

**Tasks**
- [x] Add beta message to Nightscout Status homepage
- [x] Write instructions to join beta (md file in repo?)

**Maybe?**
- [ ] Add (inactive) message at the end of Nightscout Status action responses, notifying users of Gluco Check ?
- [ ] When someone invokes Nightscout Status, send them an email to introduce Gluco Check ?

**Comment by nielsmaerten** [comment]
https://github.com/nielsmaerten/nightscout-assistant/pull/115
