### ISSUE TITLE
Merge gluco-check-frontend

### ISSUE THREAD

**Issue by nielsmaerten** [nielsmaerten/gluco-check#95]
# Merging `frontend` into `main`

### TODO:
- [ ] Update documentation (yarn 2, frontend, ...)
- [x] yarn upgrade-interactive ==> see #96 and #97
- [x] Merge github workflows
- [ ] Try merging firebaserc and firebase.json

## References
* PR #90 (prepare main repo for merge) 
* https://github.com/ddamico/gluco-check-frontend/pull/54 (prepare frontend repo for merge)

**Comment by ddamico** [comment]
@nielsmaerten Excited to work on this tomorrow! Just want to make sure going into it that

**Comment by ddamico** [comment]
@nielsmaerten haha whoops clicked the wrong button, definitely did NOT mean to close this. Excited to work on this tomorrow!!

**Comment by nielsmaerten** [comment]
Closing this. Created a separate issue for docs updates: #102
